dep 'apt' do
  met? do
    return true if grep(/^# Generated by babushka/, '/etc/apt/sources.list')
    confirm("Sould we change to simple source list for Debian? (y/n):") == "y"
  end

  meet do
    '/etc/apt/sources.list'.p.copy('/etc/apt/sources.list.backup')
 
    debian_version = shell('cat /etc/debian_version').split('/').first
    render_erb "apt/sources.list.#{debian_version}", :to => '/etc/apt/sources.list'
  end

  after { sudo 'apt-get update -y' }
end
