dep 'gemrc', :username do
  met? do
    shell? "diff -I '# Generated by babushka' #{source_path} #{gemrc_path}"
  end

  meet do
    render_erb 'gem/gemrc', to: gemrc_path
    shell "chown #{username}:#{username} #{gemrc_path}"
  end

  def gemrc_path
    if username == 'root'
      "/root/.gemrc"
    else
      "/home/#{username}/.gemrc"
    end
  end

  def source_path
    @source_path ||= erb_path_for 'gem/gemrc'
  end
end

# passenger runtime is ruby version agnostic,
# thus no need to install under each username
# and passenger will always stay under root user
# for easier update and management
dep 'passenger' do
  met? do
    shell? "gem list --local passenger | grep passenger", as: 'root'
  end

  meet do
    shell "gem install --no-ri --no-rdoc passenger", as: 'root'
  end
end
