meta :copy do
  accepts_value_for :source
  accepts_value_for :path
  accepts_value_for :comment
  accepts_value_for :username

  template do
    met? do
      next false if !path.p.exists?
      next true  if !shell?("grep '#{c} Generated by babushka' #{path}")

      shell?("diff -I '#{c} Generated by babushka' #{s} #{path}")
    end

    meet do
      render_erb source, to: path
      shell "chown #{u}:#{u} #{path}"
    end

    def u
      username.nil? ? 'root' : username
    end

    def s
      erb_path_for source
    end

    def c
      comment.nil? ? '#' : comment
    end
  end
end
