meta :copy do
  accepts_values_for :source, :path, :username

  template do
    met? do
      next false if !path.p.exists?
      next true  if !shell?("grep '# Generated by babushka' #{path}")

      shell?("diff -I '# Generated by babushka' #{source} #{path}")
    end

    meet do
      render_erb source, to: path
      shell "chown #{u}:#{u} #{path}"
    end

    def u
      username.nil? ? 'root' : username
    end
  end
end
