meta :copy do
  accepts_value_for :source
  accepts_value_for :path
  accepts_value_for :username

  template do
    met? do
      puts 'AAAAA'
      puts 'path'
      puts path.p
      puts !path.p.exists?
      puts 'shelll'
      puts !shell?("grep '# Generated by babushka' #{path}")
      puts 'test'
      puts shell?("diff -I '# Generated by babushka' #{source} #{path}")
      puts 'source'
      puts source
      puts path
      next false if !path.p.exists?
      next true  if !shell?("grep '# Generated by babushka' #{path}")

      shell?("diff -I '# Generated by babushka' #{source} #{path}")
    end

    meet do
      render_erb source, to: path
      shell "chown #{u}:#{u} #{path}"
    end

    def u
      username.nil? ? 'root' : username
    end
  end
end
