#!/bin/sh

# ssh can send dedicated VIMUSER, so each ssh user has own vim profile
# at your local machine, define VIMUSER and send it to server
#
# local machine: $HOME/.ssh/config file:
# Host *
#   SendEnv VIMUSER
#
# local machine: $HOME/.zshrc
# export VIMUSER=priit
# 

# default v command fallback is priit
/usr/bin/vim $*
